- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: ~/.dotfiles
    version: master
  register: clone_dotfiles

- name: Create dotfile symlink files
  ansible.builtin.file:
    src: "{{ clone_dotfiles.dest }}/{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: '0600'
    state: link
  loop: "{{ symlink_files }}"

- name: Create dotfile symlinks dirs
  ansible.builtin.file:
    src: "{{ clone_dotfiles.dest }}/{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: '0700'
    state: link
  loop: "{{ symlink_dirs }}"
