- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: ~/.dotfiles
    version: master
  register: clone_dotfiles

- name: Create dotfile symlink
  ansible.builtin.file:
    src: "{{ item | selectattr('src', clone_dotfiles.dest + '/' + item) }}"
    dest: "{{ item | selectattr('dest', '~/.{{ item }}') }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "{{ item | selectattr('mode', '0600') }}"
    state: link
  loop: "{{ symlinks }}"
