- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: Check for oh-my-zsh directory
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: install_directory

- name: Install oh-my-zsh
  when: not install_directory.stat.exists
  block:
    - name: Download oh-my-zsh installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/oh-my-zsh-installer.sh
        mode: 0755
    
    - name: Run oh-my-zsh installer
      ansible.builtin.command: /tmp/oh-my-zsh-installer.sh --unattended

- name: Set zsh as shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Check if roboto_mono installed
  ansible.builtin.stat:
    path: /usr/local/share/fonts/roboto_mono
  register: font_directory_stat

- name: Install nerd font
  when: not font_directory_stat.stat.exists
  block:
    - name: Create fonts directory
      become: true
      ansible.builtin.file:
        path: "{{ font_directory }}"
        owner: root
        group: root
        mode: "0755"
        state: directory
    - name: Download Roboto Mono archive
      become: true
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/RobotoMono.zip"
        dest: "{{ fonts_directory }}"
        remote_src: true
        owner: root
        group: root
        mode: "0644"
    - name: Run restorecon
      become: true
      ansible.builtin.command: "restorecon -vFr {{ fonts_directory.path }}"
    - name: Update font cache
      become: true
      ansible.builtin.command: fc-cache -v

