- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Bootstrap
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Create ssh dir
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        owner: "tom"
        group: "tom"
        mode: "0755"
    - name: Copy ssh key
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        owner: "tom"
        group: "tom"
        mode: "0600"
    - name: Set ssh config
      ansible.builtin.copy:
        content: |
          Host github.com
            StrictHostKeyChecking no
        dest: ~/.ssh/config
        owner: "tom"
        group: "tom"
        mode: "0600"
      # Create i3 directory if it doesn't exist
      # This allows us to test the dotfile file replacement behaviour
    - name: Check for i3 config dir
      ansible.builtin.stat:
        path: ~/.config/i3
      register: i3_dir
    - name: Create i3 config dir
      ansible.builtin.file:
        path: ~/.config/i3
        state: directory
        owner: tom
        group: tom
      when: not i3_dir.stat.exists
    - name: Create Root Directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - /etc/X11
        - /etc/X11/xorg.conf.d
        - /usr/share/backgrounds
        - /etc/lightdm

- name: Run playbook
  ansible.builtin.import_playbook: ../../site.yaml
