- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Bootstrap
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Create ssh dir
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        owner: "tom"
        group: "tom"
        mode: "0755"
    - name: Copy ssh key
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        owner: "tom"
        group: "tom"
        mode: "0600"
    - name: Set ssh config
      ansible.builtin.copy:
        content: |
          Host github.com
            StrictHostKeyChecking no
        dest: ~/.ssh/config
        owner: "tom"
        group: "tom"
        mode: "0600"

- name: Run playbook
  ansible.builtin.import_playbook: ../../site.yaml
